# Format:
# <classname>: false - don't include this class
# <classname>: true - include and use the defaults
# <classname>:
#   <param>: <value> - include and override the default(s)
#
# See params.pp in each class for what options are available

--- 
  network: {}
  ntp: 
    autoupdate: false
    broadcastclient: false
    config: /etc/ntp.conf
    config_template: ntp/ntp.conf.erb
    disable_auth: false
    disable_monitor: true
    fudge: []
    driftfile: /var/lib/ntp/drift
    leapfile: 
    logfile: 
    iburst_enable: true
    keys_enable: false
    keys_file: /etc/ntp/keys
    keys_controlkey: ""
    keys_requestkey: ""
    keys_trusted: []
    minpoll: 
    maxpoll: 
    package_ensure: present
    package_manage: true
    package_name: 
      - ntp
    panic: 
    peers: []
    preferred_servers: []
    restrict: 
      - "default nomodify notrap nopeer noquery"
      - "127.0.0.1"
      - "::1"
    interfaces: []
    servers: 
      - "0.fedora.pool.ntp.org"
      - "1.fedora.pool.ntp.org"
      - "2.fedora.pool.ntp.org"
      - "3.fedora.pool.ntp.org"
    service_enable: true
    service_ensure: running
    service_manage: true
    service_name: ntpd
    stepout: 
    tinker: false
    udlc: false
    udlc_stratum: "10"