--- 
  :log_dir: "./log"
  :log_name: configuration.log
  :log_level: debug
  :no_prefix: false
  :mapping: {}
  :answer_file: "~/cluster-installer-answers.yaml"
  :installer_dir: "."
  :modules_dir: "./modules"
  :default_values_dir: /tmp
  :colors: true
  :color_of_background: :dark
  :hook_dirs: []
  :custom: {}
  :low_priority_modules: []
  :name: cluster-installer
  :password: Yo8DIaRgY6CkdIn-dJrt8-DfvMglmWzQ99kr0Qutg5I
